name: Update Branch from Public Directory

on:
  push:
    branches:
      - test-branch

permissions:
  contents: write

jobs:
  update_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Check out public branch
        uses: actions/checkout@v4
        with:
          ref: 'public'

      - name: Fetch test-branch
        run: git fetch origin test-branch

      - name: Update log file
        run: |
          current_time=$(date +"%s")
          echo $current_time >> log.txt

      - name: Clean branch
        run: |
          # Remove all files from the branch
          git rm -rf .

      - name: Copy public directory from test-branch contents to root
        run: |
          git checkout origin/test-branch -- public

      - name: Move public directory contents to top-level
        run: |
          # Move contents of the public directory to the root
          mv public/* .

          git rm -rf ./public

      - name: Commit and push changes
        run: |
          # Commit the changes
          git config --global user.name 'Christopher Klix'
          git config --global user.email 'christopherklix@users.noreply.github.com'

          git add .

          git commit -m "Updated public directory from test-branch"

          # Push the new branch to the remote repository
          git push
