name: Update Branch from Public Directory

on:
  push:
    branches:
      - test-branch

jobs:
  create_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Checkout public branch
        run: |
          git checkout public

      - name: Copy public directory from test-branch contents to root
        run: |
          git restore --source test-branch ./public

      - name: Move public directory contents to top-level
        run: |
          # Move contents of the public directory to the root
          mv public/* .

          git rm -rf ./public

      - name: Commit and push changes
        run: |
          # Commit the changes
          git config --global user.name 'Christopher Klix'
          git config --global user.email 'christopherklix@users.noreply.github.com'

          git add .

          git commit -m "Updated public directory from test-branch"

          # Push the new branch to the remote repository
          git push origin HEAD
